In [ ]:
import pickle
import sys
import pandas as pd
import os

percorso_file = "LSWMD.pkl\LSWMD.pkl"

# 1. Controlliamo se il file è integro (dovrebbe pesare quasi 2 GB)
dimensione_mb = os.path.getsize(percorso_file) / (1024 * 1024)
print(f"Dimensione del file: {dimensione_mb:.2f} MB")

if dimensione_mb < 1000:
    print("⚠️ ATTENZIONE: Il file è troppo piccolo! Il download o l'estrazione sono falliti.")
    print("Devi riscaricare il file LSWMD.pkl.")
else:
    print("Il file sembra integro, provo a caricarlo...")
    
    # 2. Riapplichiamo la patch per l'indice di Pandas
    sys.modules['pandas.indexes'] = pd.core.indexes
    sys.modules['pandas.indexes.base'] = pd.core.indexes.base

    # 3. Bypassiamo pd.read_pickle e usiamo il modulo pickle nativo
    with open(percorso_file, "rb") as f:
        # L'encoding 'latin1' è fondamentale per i pickle creati in Python 2
        df = pickle.load(f, encoding="latin1")

    print("Caricamento completato con successo!")
    display(df.head())

Dimensione del file: 1998.43 MB
Il file sembra integro, provo a caricarlo...
Caricamento completato con successo!

,waferMap,dieSize,lotName,waferIndex,trianTestLabel,failureType
0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,1.0,[[Training]],[[none]]
1,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,2.0,[[Training]],[[none]]
2,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,3.0,[[Training]],[[none]]
3,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,4.0,[[Training]],[[none]]
4,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,5.0,[[Training]],[[none]]

In [ ]:
import numpy as np
def is_valid_label(x):
    # Se il valore è una lista o un array numpy, controlla che la lunghezza sia maggiore di 0
    if isinstance(x, (list, np.ndarray)):
        return len(x) > 0
    # Altrimenti, verifica semplicemente che non sia NaN
    return pd.notna(x)

# 1. Applichiamo il filtro al DataFrame
df = df[df['trianTestLabel'].apply(is_valid_label)]

# 2. Resettiamo l'indice (opzionale ma fortemente consigliato dopo aver droppato righe)
df = df.reset_index(drop=True)

# Mostriamo quante righe sono rimaste
print(f"Righe rimanenti dopo la pulizia: {len(df)}")

Righe rimanenti dopo la pulizia: 172950

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172950 entries, 0 to 172949
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   waferMap        172950 non-null  object
 1   dieSize         172950 non-null  float64
 2   lotName         172950 non-null  object
 3   waferIndex      172950 non-null  float64
 4   trianTestLabel  172950 non-null  object
 5   failureType     172950 non-null  object
dtypes: float64(2), object(4)
memory usage: 7.9+ MB

In [13]:
df.to_csv("Dataset.csv")

In [10]:
import pandas as pd

# Leggi il file pickle
df = pd.read_pickle("Dataset.pkl")

# Mostra le prime 5 righe del dataset
display(df.head())

,waferMap,dieSize,lotName,waferIndex,trianTestLabel,failureType
0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,1.0,[[Training]],[[none]]
1,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,2.0,[[Training]],[[none]]
2,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,3.0,[[Training]],[[none]]
3,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,4.0,[[Training]],[[none]]
4,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",1683.0,lot1,5.0,[[Training]],[[none]]